<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>clod__</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="types.fs" />
    <Compile Include="const.fs" />
    <Compile Include="ast.fs" />
    <Compile Include="util\stringutil.fs" />
    <Compile Include="util\disjoint_sets.fs" />
    <Compile Include="util\Make.fs" />
    <Compile Include="util\int8.fs" />
    <Compile Include="util\rounding.fs" />
    <Compile Include="util\unique_ids.fs" />
    <Compile Include="util\listutil.fs" />
    <Compile Include="settings.fs" />
    <Compile Include="type_table.fs" />
    <Compile Include="util\type_utils.fs" />
    <Compile Include="initializers.fs" />
    <Compile Include="tokens.fs" />
    <Compile Include="assembly.fs" />
    <Compile Include="codegen.fs" />
    <Compile Include="reg_set.fs" />
    <Compile Include="symbols.fs" />
    <Compile Include="tacky.fs" />
    <Compile Include="cfg.fs" />
    <Compile Include="backward_dataflow.fs" />
    <Compile Include="bytes.fs" />
    <Compile Include="const_convert.fs" />
    <Compile Include="backend\assembly_symbols.fs" />
    <Compile Include="emit.fs" />
    <Compile Include="stream.fs" />
    <Compile Include="tokstream.fs" />
    <Compile Include="lex.fs" />
    <Compile Include="parse.fs" />
    <Compile Include="tacky_print.fs" />
    <Compile Include="semantic_analysis\resolve.fs" />
    <Compile Include="semantic_analysis\label_loops.fs" />
    <Compile Include="semantic_analysis\typecheck.fs" />
    <Compile Include="tacky_gen.fs" />
    <Compile Include="optimizations\optimize.fs" />
    <Compile Include="optimizations\address_taken.fs" />
    <Compile Include="backend\codegen.fs" />
    <Compile Include="backend\regalloc.fs" />
    <Compile Include="backend\replace_pseudos.fs" />
    <Compile Include="backend\instruction_fixup.fs" />
    <Compile Include="compile.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
