//! Type checking and conversion from the untyped to typed AST.
#![allow(non_snake_case)]
#![allow(clippy::possible_missing_else)]

use std::collections::{BTreeMap, BTreeSet};
use super::{Ast::*, Const::{self, Constant}, ConstConvert, Initializers::StaticInit, Symbols::{self, IdentifierAttrs, InitialValue}, TypeTable::{self, MemberDef, StructDef}, Types::Type, TypeUtils};

fn typed(e:TypedInnerExp,t:Type)->TypedExp{TypedExp{e,t}}
pub fn isLvalue(e:&TypedExp)->bool{match &e.e{TypedInnerExp::Dereference(_)|TypedInnerExp::Subscript(_,_)|TypedInnerExp::Var(_)|TypedInnerExp::String(_)|TypedInnerExp::Arrow(_,_)=>true,TypedInnerExp::Dot(x,_)=>isLvalue(x),_=>false}}
pub fn validateType(t:&Type){match t{Type::Array(e,_)=>{if !TypeUtils::is_complete(e){panic!("Array of incomplete type")}validateType(e)},Type::Pointer(t)=>validateType(t),Type::Function(p,r)=>{for t in p{validateType(t)}validateType(r)},_=>{}}}
pub fn typecheckStructDecl(d:StructDeclaration)->TypedStructDeclaration{
 if !d.members.is_empty(){if TypeTable::mem(&d.tag){panic!("Structure was already declared")}let mut names=BTreeSet::new();for m in &d.members{if !names.insert(m.memberName.clone()){panic!("Duplicate declaration of member {} in structure {}",m.memberName,d.tag)}validateType(&m.memberType);if matches!(m.memberType,Type::Function(_, _)){panic!("Can't declare structure member with function type")}if !TypeUtils::is_complete(&m.memberType){panic!("Cannot declare structure member with incomplete type")}}
 let(mut size,mut alignment,mut members)=(0usize,1usize,BTreeMap::new());for m in &d.members{let a=TypeUtils::get_alignment(&m.memberType);let offset=size.div_ceil(a)*a;alignment=alignment.max(a);size=offset+TypeUtils::get_size(&m.memberType) as usize;members.insert(m.memberName.clone(),MemberDef{member_type:m.memberType.clone(),offset});}size=size.div_ceil(alignment)*alignment;TypeTable::add_struct_definition(d.tag.clone(),StructDef{alignment,size,members});}TypedStructDeclaration{tag:d.tag,members:d.members}}
fn convert(e:TypedExp,t:Type)->TypedExp{if e.t==t{e}else{typed(TypedInnerExp::Cast(t.clone(),Box::new(e)),t)}}
pub fn getCommonType(a:&Type,b:&Type)->Type{let a=if TypeUtils::is_character(a){Type::Int}else{a.clone()};let b=if TypeUtils::is_character(b){Type::Int}else{b.clone()};if a==b{a}else if a==Type::Double||b==Type::Double{Type::Double}else if TypeUtils::get_size(&a)==TypeUtils::get_size(&b){if TypeUtils::is_signed(&a){b}else{a}}else if TypeUtils::get_size(&a)>TypeUtils::get_size(&b){a}else{b}}
fn zero(c:Constant)->bool{matches!(c,Constant::Int(0)|Constant::Long(0)|Constant::UInt(0)|Constant::ULong(0))}
fn null(e:&TypedExp)->bool{matches!(e.e,TypedInnerExp::Constant(c) if zero(c))}
fn common_pointer(a:&TypedExp,b:&TypedExp)->Type{if a.t==b.t{a.t.clone()}else if null(a){b.t.clone()}else if null(b){a.t.clone()}else if (a.t==Type::Pointer(Box::new(Type::Void))&&TypeUtils::is_pointer(&b.t))||(b.t==Type::Pointer(Box::new(Type::Void))&&TypeUtils::is_pointer(&a.t)){Type::Pointer(Box::new(Type::Void))}else{panic!("Expressions have incompatible types")}}
fn assign(e:TypedExp,t:&Type)->TypedExp{if &e.t==t{e}else if TypeUtils::is_arithmetic(&e.t)&&TypeUtils::is_arithmetic(t)||null(&e)&&TypeUtils::is_pointer(t)||(t==&Type::Pointer(Box::new(Type::Void))&&TypeUtils::is_pointer(&e.t))||(TypeUtils::is_pointer(t)&&e.t==Type::Pointer(Box::new(Type::Void))){convert(e,t.clone())}else{panic!("Cannot convert type for assignment")}}
pub fn typecheckExp(e:Exp)->TypedExp{match e{
 Exp::Var(v)=>{let t=Symbols::get(&v).symType;if matches!(t,Type::Function(_, _)){panic!("Tried to use function name as variable")}typed(TypedInnerExp::Var(v),t)},Exp::Constant(c)=>typed(TypedInnerExp::Constant(c),Const::type_of_const(c)),Exp::String(s)=>{let n=s.encode_utf16().count()+1;typed(TypedInnerExp::String(s),Type::Array(Box::new(Type::Char),n))},
 Exp::Cast(t,e)=>{validateType(&t);let e=converted(*e);if matches!((&t,&e.t),(Type::Double,Type::Pointer(_))|(Type::Pointer(_),Type::Double)){panic!("Cannot cast between pointer and double")}if t!=Type::Void&&(!TypeUtils::is_scalar(&t)||!TypeUtils::is_scalar(&e.t)){panic!("Can only cast scalar expressions to non-void type")}typed(TypedInnerExp::Cast(t.clone(),Box::new(e)),t)},
 Exp::Unary(op,e)=>{let mut e=converted(*e);match op{UnaryOperator::Not=>{if !TypeUtils::is_scalar(&e.t){panic!("A scalar operand is required")}typed(TypedInnerExp::Unary(op,Box::new(e)),Type::Int)},UnaryOperator::Complement=>{if !TypeUtils::is_integer(&e.t){panic!("Bitwise complement only valid for integer types")}if TypeUtils::is_character(&e.t){e=convert(e,Type::Int)}let t=e.t.clone();typed(TypedInnerExp::Unary(op,Box::new(e)),t)},UnaryOperator::Negate=>{if !TypeUtils::is_arithmetic(&e.t){panic!("Can only negate arithmetic types")}if TypeUtils::is_character(&e.t){e=convert(e,Type::Int)}let t=e.t.clone();typed(TypedInnerExp::Unary(op,Box::new(e)),t)}}},
 Exp::Binary(op,a,b)=>binary(op,*a,*b),Exp::Assignment(a,b)=>{let a=converted(*a);if !isLvalue(&a){panic!("left hand side of assignment is invalid lvalue")}let t=a.t.clone();let b=assign(converted(*b),&t);typed(TypedInnerExp::Assignment(Box::new(a),Box::new(b)),t)},
 Exp::Conditional(c,a,b)=>{let c=scalar(*c);let a=converted(*a);let b=converted(*b);let t=if a.t==Type::Void&&b.t==Type::Void{Type::Void}else if TypeUtils::is_pointer(&a.t)||TypeUtils::is_pointer(&b.t){common_pointer(&a,&b)}else if TypeUtils::is_arithmetic(&a.t)&&TypeUtils::is_arithmetic(&b.t){getCommonType(&a.t,&b.t)}else if a.t==b.t{a.t.clone()}else{panic!("Invalid operands for conditional")};typed(TypedInnerExp::Conditional(Box::new(c),Box::new(convert(a,t.clone())),Box::new(convert(b,t.clone()))),t)},
 Exp::FunCall(f,args)=>match Symbols::get(&f).symType{Type::Function(ps,r)=>{if ps.len()!=args.len(){panic!("Function called with wrong number of arguments")}let args=args.into_iter().zip(ps).map(|(e,t)|assign(converted(e),&t)).collect();typed(TypedInnerExp::FunCall(f,args),*r)},_=>panic!("Tried to use variable as function name")},
 Exp::Dereference(e)=>{let e=converted(*e);match e.t.clone(){Type::Pointer(t) if *t!=Type::Void=>typed(TypedInnerExp::Dereference(Box::new(e)),*t),Type::Pointer(_)=>panic!("Can't dereference pointer to void"),_=>panic!("Tried to dereference non-pointer")}},
 Exp::AddrOf(e)=>{let e=typecheckExp(*e);if !isLvalue(&e){panic!("Cannot take address of non-value")}let t=Type::Pointer(Box::new(e.t.clone()));typed(TypedInnerExp::AddrOf(Box::new(e)),t)},
 Exp::Subscript(a,b)=>{let a=converted(*a);let b=converted(*b);let (a,b,t)=if let Type::Pointer(t)=a.t.clone(){if !TypeUtils::is_complete(&t)||!TypeUtils::is_integer(&b.t){panic!("Invalid types for subscript operation")}(a,convert(b,Type::Long),*t)}else if let Type::Pointer(t)=b.t.clone(){if !TypeUtils::is_complete(&t)||!TypeUtils::is_integer(&a.t){panic!("Invalid types for subscript operation")}(convert(a,Type::Long),b,*t)}else{panic!("Invalid types for subscript operation")};typed(TypedInnerExp::Subscript(Box::new(a),Box::new(b)),t)},
 Exp::SizeOfT(t)=>{validateType(&t);if !TypeUtils::is_complete(&t){panic!("Can't apply sizeof to incomplete type")}typed(TypedInnerExp::SizeOfT(t),Type::ULong)},Exp::SizeOf(e)=>{let e=typecheckExp(*e);if !TypeUtils::is_complete(&e.t){panic!("Can't apply sizeof to incomplete type")}typed(TypedInnerExp::SizeOf(Box::new(e)),Type::ULong)},
 Exp::Dot(e,m)=>member(false,*e,m),Exp::Arrow(e,m)=>member(true,*e,m)}}
fn converted(e:Exp)->TypedExp{let e=typecheckExp(e);match e.t.clone(){Type::Struct(_) if !TypeUtils::is_complete(&e.t)=>panic!("Incomplete structure type not permitted here"),Type::Array(t,_)=>typed(TypedInnerExp::AddrOf(Box::new(e)),Type::Pointer(t)),_=>e}}
fn scalar(e:Exp)->TypedExp{let e=converted(e);if !TypeUtils::is_scalar(&e.t){panic!("A scalar operand is required")}e}
fn member(arrow:bool,e:Exp,m:String)->TypedExp{let e=converted(e);let tag=match(&e.t,arrow){(Type::Struct(t),false)=>t,(Type::Pointer(t),true) if matches!(**t,Type::Struct(_))=>if let Type::Struct(tag)=&**t{tag}else{unreachable!()},_=>panic!("{} operator can only be applied to {}structure",if arrow{"Arrow"}else{"Dot"},if arrow{"pointers to "}else{"expressions with "})};let t=TypeTable::find(tag).members.get(&m).unwrap_or_else(||panic!("Struct type {tag} has no member {m}")).member_type.clone();typed(if arrow{TypedInnerExp::Arrow(Box::new(e),m)}else{TypedInnerExp::Dot(Box::new(e),m)},t)}
fn binary(op:BinaryOperator,a:Exp,b:Exp)->TypedExp{let a=converted(a);let b=converted(b);use BinaryOperator::*;match op{
 And|Or=>{if !TypeUtils::is_scalar(&a.t)||!TypeUtils::is_scalar(&b.t){panic!("A scalar operand is required")}typed(TypedInnerExp::Binary(op,Box::new(a),Box::new(b)),Type::Int)},
 Add=>arith_or_pointer(op,a,b,false),Subtract=>arith_or_pointer(op,a,b,true),Multiply|Divide|Mod=>{if !TypeUtils::is_arithmetic(&a.t)||!TypeUtils::is_arithmetic(&b.t){panic!("Can only multiply arithmetic types")}let t=getCommonType(&a.t,&b.t);if op==Mod&&t==Type::Double{panic!("Can't apply % to double")}typed(TypedInnerExp::Binary(op,Box::new(convert(a,t.clone())),Box::new(convert(b,t.clone()))),t)},
 Equal|NotEqual=>{let t=if TypeUtils::is_pointer(&a.t)||TypeUtils::is_pointer(&b.t){common_pointer(&a,&b)}else if TypeUtils::is_arithmetic(&a.t)&&TypeUtils::is_arithmetic(&b.t){getCommonType(&a.t,&b.t)}else{panic!("Invalid operands for equality")};typed(TypedInnerExp::Binary(op,Box::new(convert(a,t.clone())),Box::new(convert(b,t))),Type::Int)},
 LessThan|LessOrEqual|GreaterThan|GreaterOrEqual=>{let t=if TypeUtils::is_arithmetic(&a.t)&&TypeUtils::is_arithmetic(&b.t){getCommonType(&a.t,&b.t)}else if TypeUtils::is_pointer(&a.t)&&a.t==b.t{a.t.clone()}else{panic!("invalid types for comparisons")};typed(TypedInnerExp::Binary(op,Box::new(convert(a,t.clone())),Box::new(convert(b,t))),Type::Int)}}}
fn arith_or_pointer(op:BinaryOperator,a:TypedExp,b:TypedExp,sub:bool)->TypedExp{if TypeUtils::is_arithmetic(&a.t)&&TypeUtils::is_arithmetic(&b.t){let t=getCommonType(&a.t,&b.t);return typed(TypedInnerExp::Binary(op,Box::new(convert(a,t.clone())),Box::new(convert(b,t.clone()))),t)}if TypeUtils::is_complete_pointer(&a.t)&&TypeUtils::is_integer(&b.t){let t=if sub&&a.t==b.t{Type::Long}else{a.t.clone()};return typed(TypedInnerExp::Binary(op,Box::new(a),Box::new(convert(b,Type::Long))),t)}if !sub&&TypeUtils::is_complete_pointer(&b.t)&&TypeUtils::is_integer(&a.t){let t=b.t.clone();return typed(TypedInnerExp::Binary(op,Box::new(convert(a,Type::Long)),Box::new(b)),t)}if sub&&TypeUtils::is_pointer(&a.t)&&a.t==b.t{return typed(TypedInnerExp::Binary(op,Box::new(a),Box::new(b)),Type::Long)}panic!("invalid operands for addition/subtraction")}

fn zero_init(t:&Type)->Vec<StaticInit>{vec![StaticInit::ZeroInit(TypeUtils::get_size(t) as i32)]}
fn static_init(t:&Type,i:Initializer)->Vec<StaticInit>{match(t,i){
 (Type::Array(e,n),Initializer::SingleInit(Exp::String(s))) if TypeUtils::is_character(e)=>{let diff=*n as isize-s.encode_utf16().count() as isize;if diff<0{panic!("string is too long for initializer")}let mut v=vec![StaticInit::StringInit(s,diff>0)];if diff>1{v.push(StaticInit::ZeroInit((diff-1) as i32))}v},
 (Type::Pointer(e),Initializer::SingleInit(Exp::String(s))) if **e==Type::Char=>vec![StaticInit::PointerInit(Symbols::addString(s))],
 (_,Initializer::SingleInit(Exp::Constant(c))) if zero(c)=>zero_init(t),(_,Initializer::SingleInit(Exp::Constant(c))) if TypeUtils::is_arithmetic(t)=>vec![match ConstConvert::convert(t,c){Constant::Char(x)=>StaticInit::CharInit(x),Constant::UChar(x)=>StaticInit::UCharInit(x),Constant::Int(x)=>StaticInit::IntInit(x),Constant::Long(x)=>StaticInit::LongInit(x),Constant::UInt(x)=>StaticInit::UIntInit(x),Constant::ULong(x)=>StaticInit::ULongInit(x),Constant::Double(x)=>StaticInit::DoubleInit(x)}],
 (Type::Array(e,n),Initializer::CompoundInit(xs))=>{if xs.len()>*n{panic!("Too many values in static initializer")}let count=xs.len();let mut v=xs.into_iter().flat_map(|x|static_init(e,x)).collect::<Vec<_>>();if count<*n{v.push(StaticInit::ZeroInit((TypeUtils::get_size(e) as usize*(*n-count)) as i32))}v},
 (Type::Struct(tag),Initializer::CompoundInit(xs))=>{let def=TypeTable::find(tag);let ms=TypeTable::get_members(tag);if xs.len()>ms.len(){panic!("Too many elements in struct initializer")}let mut v=Vec::new();let mut offset=0;for(m,x)in ms.into_iter().zip(xs){if offset<m.offset{v.push(StaticInit::ZeroInit((m.offset-offset)as i32))}v.extend(static_init(&m.member_type,x));offset=m.offset+TypeUtils::get_size(&m.member_type)as usize}if offset<def.size{v.push(StaticInit::ZeroInit((def.size-offset)as i32))}v},_=>panic!("invalid static initializer")}}
fn make_zero(t:&Type)->TypedInitializer{match t{Type::Array(e,n)=>TypedInitializer::CompoundInit(t.clone(),(0..*n).map(|_|make_zero(e)).collect()),Type::Struct(tag)=>TypedInitializer::CompoundInit(t.clone(),TypeTable::get_members(tag).iter().map(|m|make_zero(&m.member_type)).collect()),Type::Char|Type::SChar=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::Char(0)),t.clone())),Type::UChar=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::UChar(0)),t.clone())),Type::Int=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::Int(0)),t.clone())),Type::UInt=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::UInt(0)),t.clone())),Type::Long=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::Long(0)),t.clone())),Type::ULong|Type::Pointer(_)=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::ULong(0)),t.clone())),Type::Double=>TypedInitializer::SingleInit(typed(TypedInnerExp::Constant(Constant::Double(0.)),t.clone())),_=>panic!("can't create zero initializer")}}
fn init(t:&Type,i:Initializer)->TypedInitializer{match(t,i){(Type::Array(e,n),Initializer::SingleInit(Exp::String(s))) if TypeUtils::is_character(e)&&s.encode_utf16().count()<=*n=>TypedInitializer::SingleInit(typed(TypedInnerExp::String(s),t.clone())),(Type::Struct(tag),Initializer::CompoundInit(xs))=>{let ms=TypeTable::get_members(tag);if xs.len()>ms.len(){panic!("Too many elements in structure initializer")}let count=xs.len();let mut v=xs.into_iter().zip(&ms).map(|(x,m)|init(&m.member_type,x)).collect::<Vec<_>>();v.extend(ms[count..].iter().map(|m|make_zero(&m.member_type)));TypedInitializer::CompoundInit(t.clone(),v)},(Type::Array(e,n),Initializer::CompoundInit(xs))=>{if xs.len()>*n{panic!("too many values in initializer")}let count=xs.len();let mut v=xs.into_iter().map(|x|init(e,x)).collect::<Vec<_>>();v.extend((count..*n).map(|_|make_zero(e)));TypedInitializer::CompoundInit(t.clone(),v)},(_,Initializer::SingleInit(e))=>TypedInitializer::SingleInit(assign(converted(e),t)),_=>panic!("Can't initialize scalar value from compound initializer")}}

fn local_var(d:VariableDeclaration)->TypedVariableDeclaration{if d.varType==Type::Void{panic!("No void declarations")}validateType(&d.varType);match d.storageClass{Some(StorageClass::Extern)=>{if d.init.is_some(){panic!("initializer on local extern declaration")}if let Some(old)=Symbols::getOpt(&d.name){if old.symType!=d.varType{panic!("Variable redeclared with different type")}}else{Symbols::addStaticVar(&d.name,d.varType.clone(),true,InitialValue::NoInitializer)}TypedVariableDeclaration{name:d.name,varType:d.varType,init:None,storageClass:d.storageClass}},_ if !TypeUtils::is_complete(&d.varType)=>panic!("Cannot define a variable with an incomplete type"),Some(StorageClass::Static)=>{let value=d.init.map(|i|InitialValue::Initial(static_init(&d.varType,i))).unwrap_or_else(||InitialValue::Initial(zero_init(&d.varType)));Symbols::addStaticVar(&d.name,d.varType.clone(),false,value);TypedVariableDeclaration{name:d.name,varType:d.varType,init:None,storageClass:d.storageClass}},None=>{Symbols::addAutomaticVar(&d.name,d.varType.clone());TypedVariableDeclaration{name:d.name,varType:d.varType.clone(),init:d.init.map(|i|init(&d.varType,i)),storageClass:None}}}}
fn function(mut f:FunctionDeclaration)->TypedFunctionDeclaration{validateType(&f.funType);let(ps,r)=match f.funType.clone(){Type::Function(ps,r)=>(ps.into_iter().map(|t|match t{Type::Array(e,_)=>Type::Pointer(e),Type::Void=>panic!("No void params allowed"),t=>t}).collect::<Vec<_>>(),r),_=>panic!("function has non-function type")};if matches!(*r,Type::Array(_, _)){panic!("A function cannot return an array")}let ft=Type::Function(ps.clone(),r.clone());let has=f.body.is_some();if has&&!( (*r==Type::Void||TypeUtils::is_complete(&r))&&ps.iter().all(TypeUtils::is_complete)){panic!("Can't define a function with incomplete return type or parameter type")}let current=f.storageClass!=Some(StorageClass::Static);let(defined,global)=match Symbols::getOpt(&f.name){Some(old)=>{if old.symType!=ft{panic!("Redeclared function with a different type")}match old.attrs{IdentifierAttrs::FunAttr(a)=>{if a.defined&&has{panic!("Defined function twice")}if a.global&&f.storageClass==Some(StorageClass::Static){panic!("Static function declaration follows non-static")}(a.defined||has,a.global)},_=>panic!("symbol has non-function attributes")}},None=>(has,current)};Symbols::addFun(&f.name,ft.clone(),global,defined);if has{for(p,t)in f.params.iter().zip(ps){Symbols::addAutomaticVar(p,t)}}let body=f.body.take().map(|b|block(&r,b));TypedFunctionDeclaration{name:f.name,funType:ft,params:f.params,body,storageClass:f.storageClass}}
fn statement(ret:&Type,s:Statement)->TypedStatement{match s{Statement::Return(Some(e))=>{if *ret==Type::Void{panic!("void function cannot return a value")}TypedStatement::Return(Some(assign(converted(e),ret)))},Statement::Return(None)=>if *ret==Type::Void{TypedStatement::Return(None)}else{panic!("non-void function must return a value")},Statement::Expression(e)=>TypedStatement::Expression(converted(e)),Statement::If(c,a,b)=>TypedStatement::If(scalar(c),Box::new(statement(ret,*a)),b.map(|b|Box::new(statement(ret,*b)))),Statement::Compound(b)=>TypedStatement::Compound(block(ret,b)),Statement::While(c,b,id)=>TypedStatement::While(scalar(c),Box::new(statement(ret,*b)),id),Statement::DoWhile(b,c,id)=>TypedStatement::DoWhile(Box::new(statement(ret,*b)),scalar(c),id),Statement::For(i,c,p,b,id)=>{let i=match i{ForInit::InitDecl(d)=>{if d.storageClass.is_some(){panic!("Storage class not permitted in for header")}TypedForInit::InitDecl(local_var(d))},ForInit::InitExp(e)=>TypedForInit::InitExp(e.map(converted))};TypedStatement::For(i,c.map(scalar),p.map(converted),Box::new(statement(ret,*b)),id)},Statement::Null=>TypedStatement::Null,Statement::Break(x)=>TypedStatement::Break(x),Statement::Continue(x)=>TypedStatement::Continue(x)}}
fn block(ret:&Type,b:Block)->TypedBlock{TypedBlock(b.0.into_iter().map(|x|match x{BlockItem::Stmt(s)=>TypedBlockItem::Stmt(statement(ret,s)),BlockItem::Decl(d)=>TypedBlockItem::Decl(local_decl(d))}).collect())}
fn local_decl(d:Declaration)->TypedDeclaration{match d{Declaration::VarDecl(d)=>TypedDeclaration::VarDecl(local_var(d)),Declaration::FunDecl(f)=>TypedDeclaration::FunDecl(function(f)),Declaration::StructDecl(d)=>TypedDeclaration::StructDecl(typecheckStructDecl(d))}}
fn global_var(d:VariableDeclaration)->TypedVariableDeclaration{if d.varType==Type::Void{panic!("void variables not allowed")}validateType(&d.varType);let proposed=match d.init{Some(i)=>InitialValue::Initial(static_init(&d.varType,i)),None if d.storageClass==Some(StorageClass::Extern)=>InitialValue::NoInitializer,None=>InitialValue::Tentative};if !TypeUtils::is_complete(&d.varType)&&proposed!=InitialValue::NoInitializer{panic!("Can't define variable with incomplete type")}let current=d.storageClass!=Some(StorageClass::Static);let(global,value)=match Symbols::getOpt(&d.name){Some(old)=>{if old.symType!=d.varType{panic!("Variable redeclared with different type")}match old.attrs{IdentifierAttrs::StaticAttr(a)=>{let g=if d.storageClass==Some(StorageClass::Extern){a.global}else if current==a.global{current}else{panic!("Conflicting variable linkage")};let v=match(a.init,proposed){(InitialValue::Initial(_),InitialValue::Initial(_))=>panic!("Conflicting global variable definition"),(x@InitialValue::Initial(_),_)=>x,(InitialValue::Tentative,InitialValue::Tentative|InitialValue::NoInitializer)=>InitialValue::Tentative,(_,x@InitialValue::Initial(_))|(InitialValue::NoInitializer,x)=>x};(g,v)},_=>panic!("file-scope variable has wrong attributes")}},None=>(current,proposed)};Symbols::addStaticVar(&d.name,d.varType.clone(),global,value);TypedVariableDeclaration{name:d.name,varType:d.varType,init:None,storageClass:d.storageClass}}
/// Type-check a resolved program and populate the symbol/type tables.
pub fn typecheck(p:UntypedProgram)->TypedProgram{TypedProgram(p.0.into_iter().map(|d|match d{Declaration::FunDecl(f)=>TypedDeclaration::FunDecl(function(f)),Declaration::VarDecl(d)=>TypedDeclaration::VarDecl(global_var(d)),Declaration::StructDecl(d)=>TypedDeclaration::StructDecl(typecheckStructDecl(d))}).collect())}
